
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster" // Import Toaster for potential notifications

export const metadata: Metadata = {
  title: 'CanvasCraft by Firebase Studio',
  description: 'A feature-rich web paint application generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> {/* suppressHydrationWarning might be needed with complex client-side UI */}
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        {children}
        <Toaster /> {/* Add Toaster here for app-wide notifications */}
        </body>
    </html>
  );
}
